name: Continuous Integration

# this is trigger CI on push and PR for main branch only
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# this is trigger CI on all kinds of branches and PRs


on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Use Bun to install dependencies
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run linter
        run: bun run lint
      - name: Run formater
        run: bun run format

  


